table Countries
	lineageTag: d80f4e9e-f692-40bd-a732-fd4a5154ccfc

	column Country
		dataType: string
		lineageTag: 06f47413-041f-4b55-a289-e13920b29b18
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column ISO
		dataType: string
		lineageTag: c9d81c4a-0834-4e10-8ba4-0a73fbb56c64
		summarizeBy: none
		sourceColumn: ISO

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: int64
		formatString: 0
		lineageTag: eadc66f6-b82f-45ee-8522-c06ab613fe5b
		summarizeBy: count
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 874d1043-62db-401b-bb38-15837d5e45ab
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: 9590d988-3dd9-4526-a911-ed5ef4f5a0f6
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition Countries-b0e4256a-b7ec-41ab-8c7f-8fc899687149 = m
		mode: import
		source =
				let
				    Source = Web.BrowserContents("https://statisticstimes.com/geography/countries-by-continents.php"),
				    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7)"}, {"Column2", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6)"}, {"Column3", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(5), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5)"}, {"Column4", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(4), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4)"}, {"Column5", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(3), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3)"}, {"Column6", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(3) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(2), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2)"}, {"Column7", "TABLE[id='table_id'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(3) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(2) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(1), TABLE[id='table_id'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(1)"}}, [RowSelector="TABLE[id='table_id'] > * > TR"]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Extracted Table From Html", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"No", "Region 2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Country or Area", type text}, {"ISO-alpha3 Code", type text}, {"M49 Code", Int64.Type}, {"Region 1", type text}, {"Continent", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"M49 Code", "Code"}, {"Region 1", "Region"}, {"ISO-alpha3 Code", "ISO"}, {"Country or Area", "Country"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

