table Customer
	lineageTag: 65fe8bc4-adf2-4a00-852c-0024c9044f6a

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 6fd1ccf8-6e59-45b1-9e8c-a138477f08a6
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 116c6331-736e-44b5-b2bb-6c0fb57f4be5
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column CustomerAlternateKey
		dataType: string
		lineageTag: fde93e09-9f2f-4f34-92d5-5a751a556a57
		summarizeBy: none
		sourceColumn: CustomerAlternateKey

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 4bf09a4b-12f1-428c-840e-092b232382d9
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 85d0fa9c-449e-47ac-ab0b-2a55d69cdcbd
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: 70938d29-0646-46fd-a0e8-6243187c953d
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: e5167113-befe-4f59-84a3-23ad1ff349ad
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column NameStyle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 04a73697-c9c5-4dcd-9d30-3655995f4dc6
		summarizeBy: none
		sourceColumn: NameStyle

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd9b7d67-5157-478b-9e40-e79320e446f7
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 7254cccf-31d9-422a-9b14-8362f1a0ad30
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Suffix
		dataType: string
		lineageTag: 6eb7e9d7-b5bd-4787-9268-b6b6fa36f748
		summarizeBy: none
		sourceColumn: Suffix

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 5abb9e33-384f-4c9d-8580-e30b01fcca3f
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: e2cc6164-7976-48b0-a9a6-a450e3f2c1da
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 2de2b344-ae65-4134-929d-1f50162d5053
		summarizeBy: sum
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: dcaa4c62-2226-47d3-a291-6a73e7a45b2a
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: fe8d7bcc-d5ca-4525-b7d4-31dc6acd8b82
		summarizeBy: sum
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column EnglishEducation
		dataType: string
		lineageTag: 4ad97123-0c33-4845-a52c-d18049ec57fe
		summarizeBy: none
		sourceColumn: EnglishEducation

		annotation SummarizationSetBy = Automatic

	column SpanishEducation
		dataType: string
		lineageTag: 5a1ad0d2-8200-46cd-bc5a-429c71f5e760
		summarizeBy: none
		sourceColumn: SpanishEducation

		annotation SummarizationSetBy = Automatic

	column FrenchEducation
		dataType: string
		lineageTag: 89929063-6410-4338-993a-58609f6575e9
		summarizeBy: none
		sourceColumn: FrenchEducation

		annotation SummarizationSetBy = Automatic

	column EnglishOccupation
		dataType: string
		lineageTag: 4c35f06e-9633-4968-aed4-85c74c20942b
		summarizeBy: none
		sourceColumn: EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column SpanishOccupation
		dataType: string
		lineageTag: 260b6dd8-74ff-4f28-819d-e180dc4a34f2
		summarizeBy: none
		sourceColumn: SpanishOccupation

		annotation SummarizationSetBy = Automatic

	column FrenchOccupation
		dataType: string
		lineageTag: 112e36b4-cfe8-4058-b4ec-07845db3602a
		summarizeBy: none
		sourceColumn: FrenchOccupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: string
		lineageTag: da1b4ec4-6245-4483-b1da-b915d2c96c34
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: 0484ab98-1805-4771-a844-d4b41aabbade
		summarizeBy: sum
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: caf78369-7ef7-4d3f-9377-f942ebddc697
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column AddressLine2
		dataType: string
		lineageTag: 73cde1f1-c733-471d-be99-e0ff1c0f565b
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: ed28599e-4566-45ee-91b7-b811fc50319f
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column DateFirstPurchase
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3c5374e-f3cf-44ce-8df6-f54e25049a95
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CommuteDistance
		dataType: string
		lineageTag: f07b592b-232d-4a2d-ab05-f04b1324232b
		summarizeBy: none
		sourceColumn: CommuteDistance

		annotation SummarizationSetBy = Automatic

	partition Customer-9ab256b4-f9cb-4334-b593-908ef1e66ce6 = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost", "AdventureworksDW2017"),
				    dbo_DimCustomer = Source{[Schema="dbo",Item="DimCustomer"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimCustomer,{"DimGeography", "FactInternetSales", "FactSurveyResponse"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

