table 'Last N Parameter'
	lineageTag: 41d91b70-c05c-4658-bcb3-77b79d172f54

	measure 'Last N Parameter Value' = SELECTEDVALUE('Last N Parameter'[Last N Parameter])
		lineageTag: 809dae40-3cf4-4332-b70e-e2cde5292090

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last N Parameter'
		dataType: int64
		formatString: 0
		lineageTag: 60eb7b95-12c6-4469-988d-f590a5c7cc2f
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	column 'num param' = 'Last N Parameter'[Last N Parameter Value]
		dataType: int64
		formatString: 0
		lineageTag: f9df6fb0-cb8a-4ada-86bd-322aa5d05685
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Last N Parameter-50c18bae-c453-4d4c-b4de-0b445e4e7543' = calculated
		mode: import
		source = GENERATESERIES(3, 12, 3)

	annotation PBI_Id = e7bb49cc23dc41e0afcd7b39c27da628

